### ISSUE TITLE
Unable to edit church "Church Test"

### ISSUE THREAD

**Issue by HermanPo** [mennonitengemeinde/church_site#110]
Church creation made on 2022-12-12

**Comment by danielpomas** [comment]
@HermanPo That is because you don't belong to that church yet. assign the church to your user and it should work

**Comment by HermanPo** [comment]
I was guessing there was a bit more to it.

Herman Neudorf

Pomas Farms
Email: ***@***.******@***.***>
Tel: 519-326-4410  Ext: 125

***@***.***
